version: 1
services:
  - type: web
    name: jo-backend
    runtime: node
    plan: free
    region: singapore
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20

  - type: web
    name: jo-frontend
    runtime: node
    plan: free
    region: singapore
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: jo-backend
          property: host
      - key: NODE_VERSION
        value: 20
